### ISSUE TITLE
Migrate to Angular 6

### ISSUE THREAD

**Issue by BlindDespair** [omridevk/ng-keyboard-shortcuts#1]
In order for our project to  be able to migrate to Angular 6, we need all dependencies with Angular peerDependency to be at 6 too. I would like to ask you do the migration. If you don't have time for it I'll create fork, migrate myself and then create PR.

**Comment by omridevk** [comment]
@BlindDespair 

Thanks for reporting the issue.
hopefully i'll get to it this week.

**Comment by BlindDespair** [comment]
Sorry if issue's original message was not written in most polite way, I edited it. I think I will do migration via fork in closest days. Would you merge my PR in that case?

**Comment by omridevk** [comment]
@BlindDespair 
No worries :)
Sorry for not getting around update the code, was a bit occupied with other projects.
Of course you may submit a PR, it will be greatly appreciated.

**Comment by omridevk** [comment]
I am planning on adding more features in the near future, while keeping the public API the same.

**Comment by omridevk** [comment]
Please make sure to replace Rxjs operators with their Pipeable counterparts.

**Comment by BlindDespair** [comment]
Feel free to review it now, I tested it on demo app.

**Comment by omridevk** [comment]
@BlindDespair 
I am sorry, I have been working on it offline, haven't seen you have already submitted a PR, I have already implemented migration to v6 including several bug fixes and other features.
Apologies for not updating the issue sooner when I started to work on it.
You may update to version 2.0.1 which now supports Angular 6, there are however a few breaking changes. 

If there is a problem, I can revert my fix, merge yours, then merge my branch so you can still use the library without being affected by the breaking changes i've introduced in version 2.0.1.

Thank you for your contribution.

**Comment by BlindDespair** [comment]
@omridevk 
No problem with me. Thanks for updating it. I would like to ask however what are those breaking changes? Because I checked readme and it seems to be same way as before.

**Comment by omridevk** [comment]
the breaking changes are:
1. Shortcut was changed to ShortcutInput.
2. setThrottleTime method was removed, as throttleTime is now set per command.
That's it.
