### ISSUE TITLE
Adding to a lazy-loaded feature module

### ISSUE THREAD

**Issue by amr-alamir** [omridevk/ng-keyboard-shortcuts#11]
I tried to add `KeyboardShortcutsModule` to a lazy-loaded feature module, It failed  with the error 
`BrowserModule has already been loaded`
how can I fix this?

**Comment by omridevk** [comment]
can you please provide a sandbox minimal example?
Thanks.

**Comment by omridevk** [comment]
I will try to look into it in the mean time.

Thanks for reporting the issue. I'll let you know if there's a workaround or a new version is needed.

**Comment by amr-alamir** [comment]
> can you please provide a sandbox minimal example?
> Thanks.

I'll prepare a stackblitz soon, thank you

**Comment by omridevk** [comment]
@amr-alamir 
Fixed here:
https://github.com/omridevk/ng-keyboard-shortcuts/commit/626153c8812dc633b0c767afdf1a71d8da69205d

Please install version 7.0.8 and let me know if the issue is resolved.

Thanks again for reporting the issue.
Re-open if persist please.

**Comment by amr-alamir** [comment]
@omridevk  Thank you, it works now.
what about the `forRoot()` part? is it OK to omit it?

**Comment by omridevk** [comment]
Nope, as we rely on two singletons services

**Comment by omridevk** [comment]
Plus, forRoot is needed to support lazy loaded modules that need to share a singleton service, which is the case in this module. The library uses a private service to manage all the registered shortcuts and their removal when a component associated with the shortcuts is destroyed. This ensure consistent behavior across multiple modules and allow the creation of an help screen that contains the list of all registered shortcuts across the app.
