### ISSUE TITLE
Support for Angular 11

### ISSUE THREAD

**Issue by vanderdill** [omridevk/ng-keyboard-shortcuts#112]
The current version for Angular 10 is warning when using Angular 11.
Although it works perfectly, aparently, on ng11, you can't do anything without using the npm flag --legacy-peer-deps.
I think it would be simply update de dependency requiriments to solve the problem

Thanks,
And congrats for the project. It's being realy useful.

**Comment by omridevk** [comment]
Thanks for reporting
I'll look into it, not sure when though I am a bit busy on other priorities at the moment.
Regardless, feel free to make a PR and i'll merge it as soon as possible.
Thanks again

**Comment by omridevk** [comment]
To be honest, I am not sure that updating the dependency will solve the issue as some of the peer dependencies are still outdated and may result in the need of running npm install with the legacy peer deps

**Comment by maidl** [comment]
Same 'issue' for angular version 12:
```
$ npm i ng-keyboard-shortcuts
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app@0.0.0
npm ERR! Found: @angular/common@12.0.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0" from ng-keyboard-shortcuts@10.1.17
npm ERR! node_modules/ng-keyboard-shortcuts
npm ERR!   ng-keyboard-shortcuts@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Maybe fixing the peer-dependencies (by adding the newer versions) in [/projects/ng-keyboard-shortcuts/package.json](https://github.com/omridevk/ng-keyboard-shortcuts/blob/11af8878662e23f602c4adab19c296a839121441/projects/ng-keyboard-shortcuts/package.json) will already do the trick.
```
"@angular/core": "^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0",
"@angular/common": "^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0",
```

**Comment by omridevk** [comment]
Yes, i'll test and see if indeed updating peer dep will solve the error.

**Comment by omridevk** [comment]
Updated to angular 13.
