### ISSUE TITLE
About the future of the project

### ISSUE THREAD

**Issue by relliv** [omridevk/ng-keyboard-shortcuts#126]
The project owner seems inactive or too busy since past year. I forked and updated for latest Angular versions. If you wish we can continue through this [fork](https://github.com/EgoistDeveloper/ng-keyboard-shortcuts) until the project owner comes back.

**Comment by wwarby** [comment]
Have you fixed the compatibility issue with RxJS 7 in your fork? I had to abandon this library nearly a year ago because it was incompatible with the latest RxJS and simply descoped the functionality at the time rather than looking for an alternative - I'd love to get that functionality back.

**Comment by relliv** [comment]
@wwarby Yes, my fork works with RxJS v6.3.0 and later. I have been fixed with this [commit](https://github.com/EgoistDeveloper/ng-keyboard-shortcuts/commit/959ed92700e969cfd0ac0ef53517d0a7c65d9107). Also, I actively maintain my fork and you can open an issue if you encounter an error or bug. You can see more details from [here](https://github.com/EgoistDeveloper/ng-keyboard-shortcuts/blob/master/README.md).

**Comment by wwarby** [comment]
Thanks @EgoistDeveloper for keeping this project alive - I've switched my codebase to use your fork and it works perfectly with Angular 13 and RxJS 7.

**Comment by omridevk** [comment]
Hi all, 
sorry I have been busy for the past year on other projects, but I am ready to fully get back to this project and it really makes me happy to see people depends on this project.
I would do the following:
1. I will update the project to the latest Angular version
2. Will resolve all issues
3. Will merge all open PRs

Sorry you had to switch to a fork version, I would be gladly accept a PR for updating Angular, if not, I will do my self.
Thank you again for the initiative, it is really appreciated.

**Comment by omridevk** [comment]
@EgoistDeveloper 
I am coming back to this project and my next task is to make the transition to the latest angular release.

**Comment by relliv** [comment]
@omridevk OK, I will send PR.

**Comment by omridevk** [comment]
I have made a PR:
https://github.com/omridevk/ng-keyboard-shortcuts/pull/134
Moved the repo to NX and upgraded to angular 13.

**Comment by omridevk** [comment]
Closing, as I am back again to working on this.
Thank you all for your assistance.
