### ISSUE TITLE
A shortcut backspace does not working

### ISSUE THREAD

**Issue by ebaptistella** [omridevk/ng-keyboard-shortcuts#14]
**Describe the bug**
I like to use shortcuts with key "backspace", but apparently its does not work.

**To Reproduce**
Define in the component.ts
```
    private shortcuts: ShortcutInput[] = [];

    ngAfterViewInit(): void {
        this.shortcuts.push(
            {
                key: ["backspace", "cmd + j"],
                preventDefault: true,
                allowIn: [AllowIn.Input],
                command: e => console.log("backspace")
            }
        );
    }
```

In html source:
`<ng-keyboard-shortcuts [shortcuts]="shortcuts"></ng-keyboard-shortcuts>`

**Expected behavior**
The behavior expected when backspace key is pressed is executed the command function, as when the combination key "cmd + j" is executed, its works.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bits
 - Browser: chrome
 - Version: 74.0.3729.131

**Additional context**
ng-keyboard-shortcuts: "^7.0.9",
@angular/core: "^7.2.4"

How to use shortcuts with key "backspace"?

**Comment by omridevk** [comment]
@ebaptistella 
First, thanks for reporting the issue.
Second, Were you able to get it to work?

Appreciate

**Comment by ebaptistella** [comment]
Hello, this code is functional, your library works as expected!
Thanks for your support.
