### ISSUE TITLE
[FEATURE REQUEST] Use regex or negative sentences to define shortcut keys

### ISSUE THREAD

**Issue by ebaptistella** [omridevk/ng-keyboard-shortcuts#16]
I would like to use negative sentences for setting the shortcut keys, or better, a regex option.

For example: In the latest version, I can define shortcuts for all numbers
```
{
    key: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
    preventDefault: true,
    allowIn: [AllowIn.Input],
    command: e => { console.log("number pressed") }
}
```
I would like to define a rule to fire an event if I press any key that is not a number, as I'm suggesting:
```
{
    key: !["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
    ...
    ...
}
```

Or better, using regex, it would be very easy:
```
{
    key: ^(?!.*[0-9]).*$,
    ...
    ...
}
```

Or simply, `key: [a-zA-Z]`

**Comment by omridevk** [comment]
I don't have too much to disagree with this feature, my only concern is with rendering the help screen, as it currently parses the key to display it, using regex will make it difficult to convey the hotkey trigger in the help menu. I need to think of a solution for that before implementing such feature, I am thinking of several solutions. will add it to the roadmap.
Thanks for the great suggestion.

**Comment by omridevk** [comment]
closing lack of interest, will open if will be relevant again.
