### ISSUE TITLE
Prevent Default not working as expected

### ISSUE THREAD

**Issue by hunzaboy** [omridevk/ng-keyboard-shortcuts#18]
**Describe the bug**
I have created a single character shortcut (F).  But when press e.g Ctrl+ F, it triggers both of them. However, I don't want it to trigger my custom shortcut, as its not the complete shortcut.

`
 this.shortcuts.push({
      key: ['f'],
      label: 'Label',
      description: 'shortcut description',
      command: e => {
      },
      preventDefault: false
    });
`

**To Reproduce**
1. Create a Shortcut for Character F
2. Press Ctrl + F
3. It will open the normal find of the browser AND additionally, it runs my shortcut afterward. 

**Expected behavior**
It should not run my shortcut. 

**Additional context**

**Comment by omridevk** [comment]
Thanks, will be handled in the next release. hopefully by the end of next week.

**Comment by omridevk** [comment]
will hopefully release a minor release this weekend to address this issue, thank you for your patience.

**Comment by omridevk** [comment]
fixed here:
https://github.com/omridevk/ng-keyboard-shortcuts/releases/tag/7.0.11
