### ISSUE TITLE
Minor Issue : Typo on the ReadMe Page

### ISSUE THREAD

**Issue by ghost** [omridevk/ng-keyboard-shortcuts#22]
**Describe the bug**
Just checking some snippets codes haven't check all yet.

**To Reproduce**
Npm js page.

  **KeyboardShortcutsModule.foRoot()**

**Expected behavior**
should be 
  **_KeyboardShortcutsModule.forRoot()_**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/19182512/58069229-fbd08a80-7bc6-11e9-8820-1340dc8c4115.JPG)

**Comment by omridevk** [comment]
@JojiePalahang 
Thanks a lot, however, this was already fixed, I haven't released a new version to NPM with the readme changes. will do so sometimes this week.
Again thanks for reporting the issue.
