### ISSUE TITLE
Shortcut modal overflows and does not scroll

### ISSUE THREAD

**Issue by jnfaerch** [omridevk/ng-keyboard-shortcuts#24]
**Describe the bug**
The modal does not scroll when higher than vh (and is not responsive)

**To Reproduce**
Adjust the vh to be less than the modal height or increase the number of shortcuts to overflow the vh

**Expected behavior**
The modal should be visible in its entirety in order for the user to see all shortcuts

**Screenshots**
![ng-keyboard-shortcuts](https://user-images.githubusercontent.com/32164538/58099935-f1b98680-7bdc-11e9-8627-a0084948d8cc.png)

**Desktop**
 - OS: Linux
 - Browser chrome, chromium, firefox and codesandbox.io
 - Version latest (Chrome: Version 74.0.3729.157 (Official Build) (64-bit))

**Smartphone**
 - NIL

**Additional context**
I am not able to find where to override the styling of the modal in order to fix it that way.
From Chrome console on scroll `[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>`
`<URL>` === https://www.chromestatus.com/features/6662647093133312

**Comment by omridevk** [comment]
@jnfaerch 
Yes I am currently aware of (prevent default inside passive event warning)
Will be fixed in the new release. 
I will try to provide a workaround later today or tomorrow.
Thanks for reporting the issue, sorry for the inconvenience.

**Comment by omridevk** [comment]
a version should be released either this weekend, or by mid next week.
Thanks for the patience.

**Comment by omridevk** [comment]
fixed in this version:
https://github.com/omridevk/ng-keyboard-shortcuts/releases/tag/7.0.11
Let me know if the issue persist.
Thanks for the reporting the bug.
