### ISSUE TITLE
ng-keyboard-shortcuts imports from rxjs/internals

### ISSUE THREAD

**Issue by Goobles** [omridevk/ng-keyboard-shortcuts#37]
**Describe the bug**
This module imports from rxjs/internals
https://github.com/omridevk/ng-keyboard-shortcuts/blob/9bbd6a8b38359f8c21697bd2da00893bb326aec4/projects/ng-keyboard-shortcuts/src/lib/ng-keyboard-shortcuts-help.component.ts#L20

This is not recommended and will increase the bundle size by including all of rxjs

**Comment by omridevk** [comment]
Thank you, will be fixed in the next release, hopefully i will get to it soon as angular 9 is released.
Thanks again for the nice catch.

**Comment by omridevk** [comment]
@Goobles 
Of course, feel free to create a PR if you wish, I will try to get it to as soon as possible.

**Comment by omridevk** [comment]
done.

**Comment by omridevk** [comment]
https://github.com/omridevk/ng-keyboard-shortcuts/releases/tag/8.2.0
