### ISSUE TITLE
Please update the peerDependencies to support Angular 8 (and later versions)

### ISSUE THREAD

**Issue by vnyre** [omridevk/ng-keyboard-shortcuts#48]
Your major package.json seems to be updated to support Angular 8 (churn #32) 

After installing version 8.2.3, i do get the npm warnings. 

npm WARN ng-keyboard-shortcuts@8.2.3 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-keyboard-shortcuts@8.2.3 requires a peer of core-js@^2.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN ng-keyboard-shortcuts@8.2.3 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.

Can we just go ahead and consider it safe to ignore the npm warnings ?

**Comment by omridevk** [comment]
@vnyre 
Yes, you may ignore them for now. I will update peerDepedency in package.json file and release a new version.
Thanks for reporting the issue.

**Comment by omridevk** [comment]
fixed here:
https://github.com/omridevk/ng-keyboard-shortcuts/pull/49

**Comment by omridevk** [comment]
Released in this version:
https://github.com/omridevk/ng-keyboard-shortcuts/releases/tag/8.2.4
Please enjoy.
Let me know if the issue persist and re-open the ticket.
And thanks again for the reporting the issue, much appreciated

**Comment by omridevk** [comment]
@vnyre 
Regarding core-js, it is only needed if you need to support non-evergreen browsers, e.g IE11, IE10, since I use some ES2015/2016 methods that needs to be polyfilled for older browsers. but if you are not planning to support those browsers, you can go a head and ignore that warning and not install core-js.

**Comment by vnyre** [comment]
Greatest thanks for your quick replies











From: Omri
Sent: ‎Friday‎, ‎January‎ ‎10‎, ‎2020 ‎1‎:‎14‎ ‎PM
To: omridevk/ng-keyboard-shortcuts
Cc: Valerie Nyre, Mention





@vnyre
Regarding core-js, it is only needed if you need to support non-evergreen browsers, e.g IE11, IE10, since I use some ES2015/2016 methods that needs to be polyfilled for older browsers. but if you are not planning to support those browsers, you can go a head and ignore that warning and not install core-js.
