### ISSUE TITLE
Compatibility with angular 9

### ISSUE THREAD

**Issue by yarres** [omridevk/ng-keyboard-shortcuts#52]
I tested to update an application to angular 9 via ` ng update @angular/cli @angular/core `, turns out it's impossible. Here's the error message :
` Package "ng-keyboard-shortcuts" has an incompatible peer dependency to "zone.js" (requires "^0.9.1", would install "0.10.2").`

I have no idea if the compatibility to angular 9 of your package is trivial or complex but that feature would be really useful very soon.

Thanks in advance, and thanks for your work on this package.

**Comment by omridevk** [comment]
I have a task to support angular 9, hopefully i will release a version this weekend, sorry for the inconvenience.
And thank you very much for reporting the issue. 
Will update this ticket once a fix is released.

**Comment by jnfaerch** [comment]
Just add `--force` to update. This library works fine in Angular 9

**Comment by yarres** [comment]
Thanks for your very prompt answer, it's appreciated.

**Comment by omridevk** [comment]
yes, the issue is just with the dependencies, I am will add depdenpot soon so these sort of problems will go away.
thanks @jnfaerch for the good advise!

**Comment by omridevk** [comment]
the library itself does not use any of angular features with breaking changes in angular 9.

**Comment by omridevk** [comment]
fixed
