### ISSUE TITLE
Incorrect dependencies in the github.io site

### ISSUE THREAD

**Issue by brantsrasmus** [omridevk/ng-keyboard-shortcuts#70]
The dependencies listed here https://omridevk.github.io/ng-keyboard-shortcuts/dependencies.html looks incorrect from what the package outputs. The dependencies listed on the site is actually the dependencies of your test application. Maybe could be a good idea to update?

**Comment by omridevk** [comment]
@brantsrasmus 
Good catch! thank you, I didn't see that the documentation generated the dependency from the wrong package.json file. 
Will update it.
Thanks a lot!

**Comment by omridevk** [comment]
@brantsrasmus 
Currently I couldn't find a way to config compodoc to to read the correct package.json, thus I have removed the dependencies page from the docs for now, until i'll find a workaround. closing for now.
