### ISSUE TITLE
cmd/ctrl + t not working in chrome

### ISSUE THREAD

**Issue by StefanKoenigMUC** [omridevk/ng-keyboard-shortcuts#78]
Hi all,

probably desired behavior, but is it possible to "overwrite" chrome's shortcuts? (cmd + t / cmd + n)? Was not able to figure out a way, prevendDefault seems to 

```
{      key: ["cmd + t"],
      label: "Commands",
      description: "sth",
      command: e => console.log(e),
      preventDefault: true
    },
```

is not working for me, a new tab is opened instead.

Thanks in advance!

**Comment by omridevk** [comment]
This seems like a browser limitation, as you can see in the sandbox:
https://codesandbox.io/s/optimistic-agnesi-7dffs?file=/src/index.js
I have used a different library, Mousetrap to demonstrate that the issue also appears there. 
Specifically "cmd +t" and "cmd +n " cannot be prevented from happening. 
I assume it is like this from UX standpoint as it would be weird for a site to disable the option for user to open a new tab or a window. but again I am not sure why this was Chrome decision. 
Thank you very much for contacting and open the issue. 
See more information about this here:
https://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w/7296303#7296303
Closing the issue for now as a known limitation.
Feel free to report any issue and thanks again for reporting this one.

**Comment by omridevk** [comment]
@StefanKoenigMUC If you can, please give a star to the repository, also feel free not to :) Hope you this library helped productivity in what you are working on.
