### ISSUE TITLE
function keys f1 to f12  not working.

### ISSUE THREAD

**Issue by ManojRamanan** [omridevk/ng-keyboard-shortcuts#8]
function keys f1 to f12  not working.

The following does not work where as it works for all other keys
this.keyboard.add([
    {
      key: "f1",
      command: () => console.log("f1"),
      preventDefault: true
  }
  ]);

**Comment by omridevk** [comment]
@ManojRamanan 
Thanks for reporting the issue, as I am currently working on Version 7.0 with a major API changes, I will include support for Functions keys as part of that release.

Thanks again for reporting the issue.

**Comment by omridevk** [comment]
The new version will have breaking changes which are necessary for proper cleanup to prevent memory leaks

**Comment by omridevk** [comment]
addressed here:
https://github.com/omridevk/ng-keyboard-shortcuts/pull/9
closing

Please update to latest version (7.0.1)
There are breaking changes, but it should be a quick refactoring. 
Didn't have the time to make schematics for easy upgrade.

**Comment by omridevk** [comment]
Please feel free to open any new issue with regards to the new breaking changes.
