### ISSUE TITLE
ctrl + t is not working

### ISSUE THREAD

**Issue by apaul76** [omridevk/ng-keyboard-shortcuts#89]
Hi ,

I am implementing 

 {  
          key: "ctrl + t",  
          label: "test",  
          description: "hello world",  
          command: () => console.log('directive cmd + e'),  
          preventDefault: true   
        }

inside the shortcuts array , but when pressing 'ctrl + t'  it is opening a new tab in browser could you please help me with it, it would be great if you can provide  me a working example

**Comment by omridevk** [comment]
Hi @avijitrockpaul 
Thank you for reporting the issue, it is currently a known limitation:
https://github.com/omridevk/ng-keyboard-shortcuts/issues/78
Can't seem to override the default behavior of this specific browser shortcut, I have checked with several shortcut libraries, like mousetrap and I don't remember the other one, but in both of them, you could not prevent default for ctrl/cmd + t  and several others (ctrl/cmd + n) 
I have tried to find a workaround but there does not seem to be one.
Maybe i'll revisit this later, closing as a limitation
and thanks again for reporting the issue :)
Hopefully you will still find it useful despite this limitation.

**Comment by omridevk** [comment]
see this article for more info:
https://www.robin-drexler.com/2015/07/07/overriding-default-browser-shortcuts/

**Comment by omridevk** [comment]
and:
https://stackoverflow.com/questions/23492793/jquery-disable-browser-shortcut-keys
https://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w/10933700#10933700

**Comment by omridevk** [comment]
@avijitrockpaul 
last stackoverflow gives the most thorough answer:
https://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w/10933700#10933700
With a list of shortcuts that cannot be captured via Javascript.

**Comment by apaul76** [comment]
Hi Omridev

I need your help

*Regards,*

*Avijit Paul*
*(Contact No. :8274801323 )*

**Comment by apaul76** [comment]
could your please share your email id
*Regards,*

*Avijit Paul*
*(Contact No. :8274801323 )*

**Comment by omridevk** [comment]
@avijitrockpaul 
Hi, my email is:
omrikatz12@gmail.com 
Feel free to email me, i'll try to response as soon as possible.
Thank you.
