### ISSUE TITLE
ng-keyboard-shortcuts disabled property is not recognized if bound to a false initialized property

### ISSUE THREAD

**Issue by domdeger** [omridevk/ng-keyboard-shortcuts#96]
When you bind a false initialized property to disabled input then the setter runs before the shortcuts input is set (when e.g. calculated in ngOnInit). The disabled property is never checked again then so the shortcuts input is set afterwards and then just registers events. 

My PR https://github.com/omridevk/ng-keyboard-shortcuts/pull/95 should fix the issue.

Thanks for this awesome library btw, it helped me and my team a lot! :)

**Comment by omridevk** [comment]
fixed in version 10.1.17

**Comment by omridevk** [comment]
Thanks @domdeger !!!
