### ISSUE TITLE
Shortcuts are inactive on disabled button in Firefox 

### ISSUE THREAD

**Issue by fidlip** [omridevk/ng-keyboard-shortcuts#97]
When I click button, and disable it immediately, keyboard shortcuts become nonfunctional in **Firefox**. It behave as expected in Chrome.

I prepared sample application in sandbox from your official example:

https://codesandbox.io/s/ng-keyboard-shortcuts-example-forked-6ow1k

**Comment by omridevk** [comment]
thank you for  reporting  the issue, I will look into it and will update the issue accordingly.

**Comment by omridevk** [comment]
I assume it is related to the fact that the button is disabled but is focused after clicked.

**Comment by fidlip** [comment]
Yes it very probably is.

**Comment by omridevk** [comment]
Duplicate of #

**Comment by omridevk** [comment]
5``
