### ISSUE TITLE
 When CapLock is on and Shift is pressed, shortcuts with alphabetic key are not triggered

### ISSUE THREAD

**Issue by Grasscropper** [omridevk/ng-keyboard-shortcuts#99]
Hey there, I think I found a bug. When CapLock is on and Shift is pressed, shortcuts with alphabetic keys are not triggered. This seems not to effect combination/sequence key shortcuts. So it works for a shortcut with key "t a" but not for one with key "k".

I used addEventListener to check how JS normally reacts and there it triggers just fine:
```
addEventListener('keypress', (e)=> {
      console.log(e);
    }))
```
![image](https://user-images.githubusercontent.com/24433510/100525413-f2af7900-31c0-11eb-810c-73b00654e7e0.png)

Any idea why this happens?

**Comment by omridevk** [comment]
@Grasscropper 
Can I reproduce it in the example app codesandbox?
https://codesandbox.io/s/yvyovny43v
I'll look into, thanks for reporting.

**Comment by Grasscropper** [comment]
> @Grasscropper
> Can I reproduce it in the example app codesandbox?
> https://codesandbox.io/s/yvyovny43v
> I'll look into, thanks for reporting.

Pfff not sure why but works absolutely fine in codesandbox but somehow not in my app...

**Comment by omridevk** [comment]
Closing, need more information.
